### ISSUE TITLE
[Intent to Implement] Vanity Contract Addresses

### ISSUE THREAD

**Issue by wjmelements** [johguse/profanity#12]
I intend to add a feature that would allow you to specify that the address you are targeting is the contract created by the private key's zeroth transaction. This would be equivalent to the `--contract` feature in https://github.com/MyEtherWallet/VanityEth, and is useful for mining vanity addresses recommended by [EIP-1167](https://eips.ethereum.org/EIPS/eip-1167).

**Comment by k06a** [comment]
Here is optimized version without RLP encoder: https://ethereum.stackexchange.com/a/47083/3032

```
contract_address = address(keccak256(byte(0xd6), byte(0x94), wallet_address, byte(0x80)));
```

**Comment by wjmelements** [comment]
Thanks!

**Comment by k06a** [comment]
Also please think of CREATE2 instruction support: https://github.com/ethereum/EIPs/blob/1d506308a84f0b766a397d04a6d9a08f295a04c8/EIPS/eip-1014.md

**Comment by wjmelements** [comment]
Completed via https://github.com/johguse/profanity/pull/15
