### ISSUE TITLE
did not start

### ISSUE THREAD

**Issue by destansi** [johguse/profanity#17]
windows 10 pro didn't work well and reinstalled. The black screen is coming and closing. rx580 video card drivers are up to date. What is missing? ethereum miner 30-32 mhs. Thanks for help.

**Comment by johguse** [comment]
profanity is a terminal program, you run it through the terminal and that's also how you supply it with the parameters it needs to run. When you run it like a normal desktop program it will just print the help and close immediately as you've observed.
