### ISSUE TITLE
New binary build for Windows

### ISSUE THREAD

**Issue by hodlbank** [johguse/profanity#18]
There are some improvements since latest binary release, e.g. --contract option support #15.
Please make a new binary release for Windows with those features.

**Comment by dukei** [comment]
So what is about a build?

**Comment by dukei** [comment]
I have managed to build it in Visual Studio 2019
You can find the solution here: https://github.com/dukei/profanity/tree/dukei-develop

Here is the latest build (with fixed matching by mask)
https://github.com/dukei/profanity/releases/tag/1.23d, enjoy

**Comment by johguse** [comment]
Sorry for not updating this project for so long, I've been lazy. Worked a bit on it over the last couple of days now and merged in all pull requests and made some other fixed. Major improvement has been done on nVidia card. My GTX 1070 went from 26MH/s to 106MH/s.
