### ISSUE TITLE
Score can never be 40

### ISSUE THREAD

**Issue by zzh1996** [johguse/profanity#20]
https://github.com/johguse/profanity/blob/9f9341028fab22efdc90c0a0be89251160f96e65/Dispatcher.cpp#L320

The score is 39 at maximum, which is buggy if you want an address with score 40.

For example, when you run`./profanity.x64 --numbers` to generate all-digits addresses, you can get an address with 39 digits (score = 39) easily. But you can never get score 40.

**Comment by ctrlcctrlv** [comment]
An address with score 40 means Ethereum's encryption is basically broken and this tool is pointless. A score of 40 is, for all intents and purposes, impossible.

**Comment by zzh1996** [comment]
No! An address with score 40 does not mean all characters are fixed, but they are in a specific range. I can get an address with 39 **digits** (score = 39) easily. Please show me how can I get an address with 40 digits (0-9).

**Comment by ctrlcctrlv** [comment]
Oh, yeah, you're right, I guess it is possible for some workloads. Submit a PR I guess :-)

**Comment by johguse** [comment]
It's fixed!
