### ISSUE TITLE
Crash on benchmark - no output

### ISSUE THREAD

**Issue by MysticRyuujin** [johguse/profanity#22]
Downloaded the release, tried to run it, got this:

```
C:\Temp\profanity-v1.3-x64>profanity.exe --benchmark
Mode: benchmark
Target: Address
Devices:
  GPU0: GeForce GTX 1070, 8589934592 bytes available, 15 compute units (precompiled = no)
  GPU1: Ellesmere, 8589934592 bytes available, 36 compute units (precompiled = no)

Initializing OpenCL...
  Creating context...
C:\Temp\profanity-v1.3-x64>
```

**Comment by johguse** [comment]
Hm. I wonder if this might have something to do with the fact that you're running both AMD and nVidia on your computer. Could you try adding either "-s 0" or "-s 1"? This skips the first or the second card and we can see if it can run on either of them at a time or not.

**Comment by MysticRyuujin** [comment]
Both `-s 0` and `-s 1` work as expected. So it's just when trying to run with both.

**Comment by johguse** [comment]
Glad to hear that. For the time being if you want to use both cards just launch two instances of the program with the same settings, one for each card. I'll see if I can get this fixed in the coming days.

**Comment by johguse** [comment]
Oh, by the way. What performance do you get on your GTX 1070 with the default settings out of the box? What's the hashrate for the benchmark?

**Comment by MysticRyuujin** [comment]
Is there a reproducible benchmark? The `--benchmark` command never seems to stop. It fluctuates a lot low of 60, high of 90, generally sitting in the ~70 MH/s range

**Comment by GentilsTo** [comment]
Add the same issue, would suggest giving some hint of this in the readme in a small troubleshooting section maybe :)
