### ISSUE TITLE
contract address generation is broken in 1.3

### ISSUE THREAD

**Issue by dukei** [johguse/profanity#23]
The generation becomes blazingly fast on nvidia! Unfortunatlely contract addresses are broken, see screenshot.

![image](https://user-images.githubusercontent.com/1279262/61531195-d0cfaf00-aa2e-11e9-8786-6109b968e769.png)

**Comment by johguse** [comment]
Just released new version, can you confirm that it works?

**Comment by dukei** [comment]
It seems to be fine now. Thank you :)
