### ISSUE TITLE
Error in kernel queueing

### ISSUE THREAD

**Issue by rtohlsen** [johguse/profanity#3]
Love the project!

However, when I run it on my local machine with a GTX 1050 3gb, for release 1.11 I get the following error:

warning: local work size abandoned on GPU0
std::runtime_error - kernel queueing failed (res = -4)

any thoughts?

**Comment by johguse** [comment]
How many devices are listed when running? Only the GTX 1050? No integrated graphics?

**Comment by rtohlsen** [comment]
Excuse my typo, GTX 1060 3gb. It is the only GPU listed, no integrated graphics.
I made a dual-boot partition and tried it on linux ubuntu desktop, and... Same Error!

Not quire sure why it would be doing this... here is the full display:

Mode: leading
Devices:
	GPU0: GeForce GTX 1060 3GB, 3157000192 bytes available, 9 compute units (precompiled = yes)

Initializing OpenCL...
	Creating context...OK
	Loading kernel from binary...OK
	Building program...OK


warning: local work size abandoned on GPU0
std::runtime_error - kernel queueing failed (res = -4)

**Comment by johguse** [comment]
During the weekend I'll work on improving debug output and add a verbose switch to use increased output. Maybe that will help in narrowing down what could be going wrong.

The -4 error code corresponds to CL_MEM_OBJECT_ALLOCATION_FAILURE. I don't believe you're running out of memory, from what I can recall the program should use a little less than 1GB of memory so there's probably something else that I'm missing.

Anyways. I'll get back to you with a new release during the weekend if you have time to try it out.

**Comment by rtohlsen** [comment]
Awesome, thanks! You rock!

**Comment by rtohlsen** [comment]
Any progress?

**Comment by memclutter** [comment]
Any progress++?

**Comment by memclutter** [comment]
Same problem on my GTX 1050 mobile with 2gb videomemory and 6gb ram. OS ubuntu 18.04

**Comment by z2vg** [comment]
Please ..error
Mode: benchmark
Devices:
        GPU0: GeForce GTX 550 Ti, 1073741824 bytes avail
recompiled = yes)

Initializing OpenCL...
        Creating context...OK
        Loading kernel from binary...OK
        Building program...OK

std::runtime_error - kernel queueing failed (res = -54)

**Comment by johguse** [comment]
I'm sorry I've been unavailable. I looked into this today and I realized I was wrong in that it uses just a little less than 1 GB. It's actually using at least 2.47 GB. I did however manage to bring it down to about 1GB. Hopefully this means that @rtohlsen and @memclutter can run it now. Please let me know if it works!

As for you @z2vg, I'm sorry to say that the 1GB memory size of the 550 Ti won't be enough. :(
