### ISSUE TITLE
Only showing first result in WIN10 command prompt

### ISSUE THREAD

**Issue by kernelsuser** [johguse/profanity#4]
Hi there, this seems like a simple problem, not sure if I'm doing something wrong, when I run profanity in Windows 10 command prompt using for instance: profanity --matching aXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX I only ever get 1 result while hashing at 60M hashes. The one result I get also always shows up before the speed starts getting displayed.

If feels like there is a line feed missing after displaying results, causing the carriage return of the Speed to overwrite any found matches.

Any ideas ? Thanks

**Comment by kernelsuser** [comment]
Tried to download the source to have a look at fixing the issue myself, but could not build due to CL/cl.h not being included in the repo ?

**Comment by johguse** [comment]
The resulting public key is scored based on the mode (in this case matching) and the program will never show two public keys with the same score, it always makes sure that the next result it shows is even better!

In the case of the matching mode it can't get any better than matching all the characters (in this case one) so it'll run forever only ever displaying one result.

This behavior is not well documented and should be polished.

If you're actually looking for any addresses starting only with an "a" then you'll get about five million results EVERY SECOND on a high end AMD graphics card. Is this really what you're looking for?

**Comment by kernelsuser** [comment]
Ahh, thanks for the explanation, yes, that does make much more sense now!
No, wasn't looking for a million wallets starting with 'a', just wanted to prove whether I could actually see more than one result, I figured that should spit out a few million results :)

That is great, will play a bit more to see what I can create! 

In the readme you mention that it should take 60 odd seconds to match 8 characters, are you able to explain a bit more  about what that means, for example, is it possible to figure out how long it would take to match a public address starting with 8 characters 0xaabbccdd  ?

Thanks for your work! Great project 👍

**Comment by johguse** [comment]
> In the readme you mention that it should take 60 odd seconds to match 8 characters, are you able to explain a bit more about what that means, for example, is it possible to figure out how long it would take to match a public address starting with 8 characters 0xaabbccdd ?

It's all probability and the number given is the average expected time. Every character in an address can be one out of 16 digits (0-f). For eight characters there's 16^8 combinations. If you're running 60 MH/s the average expected time is calculated as (16^8)/(60 * 10^6) ~= 71 seconds on average with that speed.

It can take more or less time, but on average it should be 71 seconds with 60MH/s. These times do not include the initialization time.

Thanks for the support! <3

**Comment by kernelsuser** [comment]
Now that is interesting because I had it running for hours this morning trying to get a 6 character match and never got a single result. I also now remember that I tried the match with a single starting 'a' and sometimes also didn't get a result. I will try to recreate the problem now and upload a screenshot of the command prompt.

**Comment by johguse** [comment]
That's very much a problem I'd like to fix.

Make sure that you use lowercase and omit the leading "0x".

**Comment by kernelsuser** [comment]
Ah bugger, yes, that explains it, I was trying to match on a pattern starting with a capital letter ! Will go try it now with lowercase pattern

**Comment by kernelsuser** [comment]
Yep, working great now. Thanks for answering all my noob questions!
