### ISSUE TITLE
"warning: local work size abandoned on GPU1"

### ISSUE THREAD

**Issue by admbe** [johguse/profanity#5]
I have tried using v1.21 on two different systems with the same results. One system has a GTX 1060, the other 1070Ti

If I don't issue the -I <value> it hangs after "Initializing devices..." for 10+ minutes. I have to issue a low number for it to pass this, such as profanity.exe --skip GPU0 -I 900 --matching c1. If I do that, I get "warning: local work size abandoned on GPU1"

I'll get a status of mh/s (e.g. GPU1: 18.230 MH/s"), but no results, even for something really easy, like matching 2 characters. 

Here's a screen shot - https://imgur.com/a/9rMmOTl

**Comment by johguse** [comment]
Sorry for the late response.

You have to use lowercase hexadecimal characters. So `--matching C1` should be `--matching c1`. This is not documented anywhere. I've been meaning to make it case insensitive for some time now as others have had problems with it in the past. It's an easy fix I just haven't gotten around to it.

I almost always abandon the local work size on nVidia cards, nothing to worry about really.

You're right in decreasing the -I parameter, although 10 minutes seems like too much time to be initializing. This might be a problem that I'll have to look into. I'll leave this issue open until then.

**Comment by admbe** [comment]
Sweet, that worked simply by switching to lowercase. This thing is fast! I still need to give a low number for "-I", not 100% sure of the implications of that but I was able to get what I need very quickly

Thanks
