### ISSUE TITLE
Exits immediately.

### ISSUE THREAD

**Issue by Legend-of-iPhoenix** [johguse/profanity#50]
Hello- upon launching profanity, it exits immediately. I'm on windows launching through cmd- it doesn't matter what command I use, it exits immediately regardless:
![image](https://user-images.githubusercontent.com/32944537/121582098-9d201880-c9fc-11eb-923a-350827342d13.png)

I did have something else running on my main gpu when I grabbed the screenshot, though this issue happens even if I do not.

**Comment by kngspace** [comment]
Can you skip the intel 630, probably not bale to load the work for that gpu?

**Comment by Legend-of-iPhoenix** [comment]
Ah good point; I just assumed it would use the first one on the list.
