### ISSUE TITLE
Option for scoring based on # of zero-bytes in address

### ISSUE THREAD

**Issue by mindnumbe** [johguse/profanity#57]
This tool is fantastic for finding gas efficient ethereum addresses and I typically use it with the form of `.\profanity --leading 0` for this purpose.

This outputs addresses like:
0x0000...
0x00000..
0x000000000...
All of which save significant amounts of gas through long term use.
However, gas efficiency on eth addresses is also driven through zero-bytes, not just leading zeros.

It'd be incredible if there were a scoring mechanism based on this premise of finding zero-bytes anywhere throughout the address, rather than just the beginning.

For example
Score | Address
4        | 0x**00000000**.....
5        | 0x**00000000**4124**00**1232.....
6        | 0x**000000**41**00**24**00**12**00**32.....
9 | 0x**00000000**41**00**24**00**12**00**32**0000**...

As I run through the `.\profanity --leading 0` program, I wonder how many addresses with more zero-bytes are skipped over.

For more reading on this:
https://medium.com/coinmonks/on-efficient-ethereum-addresses-3fef0596e263

**Comment by definevalue** [comment]
> __kernel void profanity_score_leading(__global mp_number * const pInverse, __global result * const pResult, __constant const uchar * const data1, __constant const uchar * const data2, const uchar scoreMax) {
>   const size_t id = get_global_id(0);
>   __global const uchar * const hash = pInverse[id].d;
>   int score = 0;
> 
>     if (pInverse[id].d[0] == 0) {
>         score = 4;            
>         for (int i = 4; i < 20; ++i) {
>           score += (hash[i] == 0);
>       }
>     }
> 
>   profanity_result_update(id, hash, pResult, score, scoreMax);
> }



> And as said, I've not maintained this project for a long time and if you're in need for more speed there's other solutions out there that are faster.
> 
> I know of at least one optimization for this project that could roughly double the speed which I missed the first time around (reflection of coordinates against the X-axis on the elliptical curve). I wrote a CUDA version which allowed for heavier optimizations that has massive speed gains on nVidia platforms which I never got around to releasing. While researching optimizations for it I found a project (can't recall the name) which had support for Ethereum vanity addressees that was just slightly faster than the CUDA version I'd put together.
> 
> Since that project already existed and was faster and I thought there wasn't room for more improvement I abandoned the CUDA version I was working on (and this OpenCL version with it).
> 
> So there's something faster out there if you need it, just so you know!

What is this other project because i've only ever seen this with GPU's for Ethereum if you dont mind me asking

**Comment by straightnun** [comment]
@mindnumbe You say, the optimization was succesful - are you building on Windows, or Linux? Ive tried building the program (even without changing code), but cant get profanity,x64 to detect my GPU, while the "default program" (profanity.exe) is running perfect.
