### ISSUE TITLE
How MH/s?

### ISSUE THREAD

**Issue by komyaka** [johguse/profanity#6]
RUSSIAN: для тестирования я запустил на 1050ti. Решил замерить скорость. Но выводимые значения не совпадают с реальностью.
G.Translate: for testing I ran on 1050ti. Decided to measure the speed. But the displayed values do not coincide with reality.

![default](https://user-images.githubusercontent.com/34284729/42202727-1b8cf734-7ea5-11e8-868d-16eb2a52dbb7.png)

> 
>   Time:     9s Score:  7 Private: 
> 0xffdf844f2239a711d1045ddb57fb41de75cf39ad0cd835d39a3c2a97409c0ef1 Public: 0xfffffff9aae9efc692ba12004feb285b9b98ca21
>   Time:    69s Score:  8 Private: 0xffdf844f223aef57d1045ddb57fb41de75cf39ad0cd835d39a3c2a97409c1298 Public: 0xffffffffe3a94a1c80aa9bf609ebd232b4517f8c

69 - 9 = 60 seconds

c1298 - c0ef1 = 3A7 or 935

935/60 = 15 combination / second

How?

**Comment by johguse** [comment]
0xFFFFFFFF <- Eight (8) F = 16^8 = 4294967296 combinations has to be done on average before hit.

With 8.8 million combinations per second average time is: 4294967296 / 8800000 = 488 seconds on average.

69 seconds is a very good time.
----
All times are probabilistic. You might get faster result, you might get slower result. On average for 8.8MH/s should be 488 seconds.

Also, the time displayed does not take into account initialization. In future version I will also include initialization time.

Все времена вероятностны. Вы можете получить более быстрый результат, вы можете получить более медленный результат. В среднем на 8,8MH / s должно составлять 488 секунд.

Кроме того, отображаемое время не учитывает инициализацию. В будущей версии я также включу время инициализации.

**Comment by johguse** [comment]
Нет извините. Я использовал программное обеспечение для перевода. : /

Теперь появилась новая версия, включающая время инициализации: https://github.com/johguse/profanity/releases/tag/v1.22

**Comment by komyak** [comment]
Спасибо! Быстро реагируете на возникшие "проблемы")

Thank you! Quickly react to the emerging "problem")

**Comment by komyak** [comment]
Пришлите пожалуйста свою почту. Есть вопросы в рамках проекта.

Please send us your email. There are issues in the framework of the project.
03 июл 2018 г. 20:44 пользователь "johguse" <notifications@github.com>
написал:

**Comment by johguse** [comment]
My initialization time on GTX 1070: 6 seconds

If you have too much initialization time then start program with -I 8200 or -I 4100 or lower. You might get slower speed but initialization will be faster.

-----

Мое время инициализации на GTX 1070: 6 секунд

Если у вас слишком много времени инициализации, тогда запустите программу с -I 8200 или -I 4100 или ниже. Вы можете получить более медленную скорость хеша, но инициализация будет ниже.

**Comment by komyak** [comment]
The speed is good. I'll try to connect Rig 8*rx580, later will write how it will work.

**Comment by SuperXMR** [comment]
![default](https://user-images.githubusercontent.com/34284729/42239640-2e9a26d6-7f0d-11e8-847c-f6d73a88921c.png)

Error... Stats bag...

**Comment by SuperXMR** [comment]
And I think it's worth adding a parameter: -o output.txt

**Comment by komyak** [comment]
Hello
