### ISSUE TITLE
[FEATURE] Start - end range

### ISSUE THREAD

**Issue by TGM** [johguse/profanity#7]
Hello,

Can you implement a start-end range for the given private key?

Example:

-r 1-10000
-r fff - fffffffffffff

**Comment by johguse** [comment]
No. There's no need for the function of the program to be able to distribute the search space between invocations on the program, either on the same computer or between many computers on a network.

Even for many cards distributed over many computers the search space is still so huuuuuuuuge that unless you're running ridiculously many cards at the same time there's basically no chance that their search spaces will overlap and work will be wasted.

They can all just randomize a seed for every GPU, overlaps are very unlikely.
