### ISSUE TITLE
[FEATURE] Match against a given list

### ISSUE THREAD

**Issue by TGM** [johguse/profanity#8]
Hello,
Can you implement a match against a given list?

Example.

address.txt
0x0000000000000000000000000000000000000001
0x0000000000000000000000000000000000000002

-a address.txt

Leading zero should be optional

**Comment by johguse** [comment]
No. It doesn't really serve any purpose unless you're trying to brute-force private keys belonging to other people. The chances that you'll succeed in doing this is vanishingly small. There are 2^256 combinations of private keys, on average you need to search 2^255 combinations before finding what you're looking for. That's a very very very very very big number.

If you're looking for certain patterns it's better to suggest a new mode that would generate the kind of addresses you're looking for. Finding an address belonging to someone else is not possible.
